#!/usr/bin/perl
# Combines data/items.json (from fetch_item_info.pl) with a parsed favorites
# list (from parse_export.pl) into one self-contained JS data module, meant
# to be pasted verbatim into an HTML Artifact's <script> block — Artifacts
# can't fetch external files, so this bakes the data in as a plain JS
# assignment rather than something an artifact would need to fetch.
#
# Usage:
#   perl parse_export.pl "KeystoneLoot:v3,..." > scratch/favorites.json
#   perl fetch_item_info.pl < item_ids_from_that_file.txt   # (see parse_export.pl output)
#   perl build_favorites_js.pl scratch/favorites.json > data/keystoneloot_favorites.js
#
# Or, since favorites JSON can also come from stdin:
#   perl parse_export.pl "KeystoneLoot:v3,..." | perl build_favorites_js.pl > data/keystoneloot_favorites.js
#
# Output: a single `const KEYSTONE_LOOT_FAVORITES = {...};` assignment,
# structured as:
#   { "<specId>": { specId, specName, items: [ { ...favorites fields,
#     ...item info fields (name, icon, iconUrl, itemLevel, slot, quality,
#     sourceLines, tooltipText, wowheadUrl) } ] } }
# Items missing from data/items.json (not yet fetched) are still included,
# with only the favorites fields and an `unresolved: true` flag, so a
# forgotten fetch fails visibly in the rendered artifact instead of silently
# dropping items.

use strict;
use warnings;
use JSON::PP;
use FindBin qw($RealBin);
use File::Spec;

binmode STDOUT, ':utf8';

my $favorites_arg = shift @ARGV;
my $favorites_text;
if (defined $favorites_arg) {
    open my $fh, '<:raw', $favorites_arg or die "Can't read $favorites_arg: $!\n";
    local $/;
    $favorites_text = <$fh>;
    close $fh;
} else {
    local $/;
    $favorites_text = <STDIN>;
}
die "No favorites JSON given (arg path or stdin), see script header for usage.\n"
    unless defined $favorites_text && length $favorites_text;

my $json = JSON::PP->new->utf8;
my $favorites = $json->decode($favorites_text);

my $repo_root  = $ENV{REPO_ROOT} // File::Spec->catdir($RealBin, '..', '..', '..', '..');
my $items_path = File::Spec->catfile($repo_root, 'data', 'items.json');

my %items;
if (-f $items_path) {
    open my $fh, '<:raw', $items_path or die "Can't read $items_path: $!\n";
    local $/;
    my $text = <$fh>;
    close $fh;
    %items = %{ $json->decode($text) } if length $text;
}

my $unresolved = 0;
for my $specKey (keys %$favorites) {
    my $spec = $favorites->{$specKey};
    for my $entry (@{ $spec->{items} }) {
        my $info = $items{ $entry->{itemId} };
        if ($info) {
            %$entry = (%$entry, %$info);
        } else {
            $entry->{unresolved} = JSON::PP::true;
            $unresolved++;
        }
    }
}

if ($unresolved) {
    warn "$unresolved item(s) have no entry in data/items.json - run fetch_item_info.pl for them first.\n";
}

print "// Generated by .claude/skills/keystoneloot-favorites/scripts/build_favorites_js.pl\n";
print "// Do not hand-edit - re-run the script chain in that skill's SKILL.md instead.\n";
# Compact, single-line JSON (not pretty-printed): this project's convention
# for large payloads, per .claude/knowledge/building-reports.md - keeps the
# `const X = {...}` line greppable/validatable as one JSON blob and avoids
# bloating the file with a 130+ KB payload's worth of indentation.
print "const KEYSTONE_LOOT_FAVORITES = ";
print JSON::PP->new->canonical->encode($favorites);
print ";\n";
